[server]
headless = true
maxUploadSize = 25

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0B6E99"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#EAF2F7"
textColor = "#17202A"
font = "sans serif"
